[2024-08-10T07:14:36.860+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-10T07:14:36.873+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETLWeatherPostgres.extract manual__2024-08-10T07:14:35.723427+00:00 [queued]>
[2024-08-10T07:14:36.876+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETLWeatherPostgres.extract manual__2024-08-10T07:14:35.723427+00:00 [queued]>
[2024-08-10T07:14:36.877+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-10T07:14:36.882+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-08-10 07:14:35.723427+00:00
[2024-08-10T07:14:36.886+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1859) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-10T07:14:36.887+0000] {standard_task_runner.py:64} INFO - Started process 1861 to run task
[2024-08-10T07:14:36.887+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETLWeatherPostgres', 'extract', 'manual__2024-08-10T07:14:35.723427+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/02_ETLWeatherPostgres.py', '--cfg-path', '/tmp/tmpty54fs9y']
[2024-08-10T07:14:36.888+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask extract
[2024-08-10T07:14:36.925+0000] {task_command.py:426} INFO - Running <TaskInstance: ETLWeatherPostgres.extract manual__2024-08-10T07:14:35.723427+00:00 [running]> on host 101007b4e0e8
[2024-08-10T07:14:36.969+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETLWeatherPostgres' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-08-10T07:14:35.723427+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-10T07:14:35.723427+00:00'
[2024-08-10T07:14:36.970+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-10T07:14:36.971+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-10T07:14:36.971+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/02_ETLWeatherPostgres.py", line 29, in extract
    r = requests.get("http://api.weatherapi.com/v1/current.json", params=payload)
        ^^^^^^^^
NameError: name 'requests' is not defined
[2024-08-10T07:14:36.979+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETLWeatherPostgres, task_id=extract, run_id=manual__2024-08-10T07:14:35.723427+00:00, execution_date=20240810T071435, start_date=20240810T071436, end_date=20240810T071436
[2024-08-10T07:14:36.986+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task extract (name 'requests' is not defined; 1861)
[2024-08-10T07:14:37.033+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-10T07:14:37.045+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-10T07:14:37.048+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
